steps:
  # Step 1: Install dependencies
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['ci']

  # Step 2: Run Sequelize migrations (DATABASE_URL comes from Secret Manager)
  - name: 'node:22'
    entrypoint: 'bash'
    secretEnv: ['DATABASE_URL']
    args:
      - '-c'
      - |
        echo "Running migrations..."
        npx sequelize-cli db:migrate

  # Step 3: Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

availableSecrets:
  secretManager:
    - versionName: projects/459713973146/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '900s'
